### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by joeblew99** [tideland/gorest#18]
I think it's possible to code gen from a swagger. What do you think ?
I could help with a OR on this but i reckon you know if it's a smart move.

**Comment by themue** [comment]
I would have to investigate in Swagger. So far I never used it. But I have to admit I'm no friend of code generators. Most I've seen led to bloated and badly maintainable code.

**Comment by dominictracey** [comment]
There's a lot to be said for the openAPI standard, such as it is.

**Comment by themue** [comment]
I currently don't have any time to investigate in this topic. But feel free to fork the repo and give it a try. Or even better another additional repo, because I try to get no 3rd party dependencies in the code.
