### ISSUE TITLE
Public function AddTokenToRequest removed

### ISSUE THREAD

**Issue by ihoff** [tideland/gorest#29]
Hi, just tried to change from 2.15.2 to 2.15.3 and found an blocking issue.
You have remove the function AddTokenToRequest from package jwt which is used in package request (see request.go [line 446](https://github.com/tideland/gorest/blob/master/request/request.go#L446) ).

You just change the patch version, i don't think this covers the  removal of a public function.

**Comment by themue** [comment]
Thanks, will fix it.
